const restorent_Data = [

    {
        id: "347774",
        name: "Varalakshmi Tiffins",
        cloudinaryImageId: "8523266de1213e8ea57e5df4eedf747e",
        locality: "Manikonda",
        areaName: "Narsingi",
        costForTwo: "₹150 for two",
        cuisines: ["South Indian", "North Indian", "Thandoori"],
        avgRating: 4.5,
        veg: true,
    },
    {
        id: "3477274",
        name: "Udipi's upgaar",
        cloudinaryImageId: "nqgrpd6e8vliz57mxlvu ",
        locality: "GAchibowlli",
        areaName: "Narsingi",
        costForTwo: "₹550 for two",
        cuisines: ["South Indian", "North Indian"],
        avgRating: 4.5,
        veg: true,
    },
    {
        id: "3477741",
        name: "ChaiPoint",
        cloudinaryImageId: "p4znxkstyrdobxwl6rxa ",
        locality: "Ameerpet",
        areaName: "Narsingi",
        costForTwo: "₹50 for two",
        cuisines: ["South Indian", "North Indian"],
        avgRating: 3.5,
        veg: true,
    },
    {
        id: "3477746",
        name: "Eat Fit",
        cloudinaryImageId: "6126c9b45de2cb222405c1af8a321e74 ",
        locality: "Kukatpalli",
        areaName: "Narsingi",
        costForTwo: "₹560 for two",
        cuisines: ["South Indian", "North Indian"],
        avgRating: 2.5,
        veg: true,
    },
    {
        id: "3477747",
        name: "SubWay",
        cloudinaryImageId: "1ace5fa65eff3e1223feb696c956b38b ",
        locality: "Kukatpalli",
        areaName: "Narsingi",
        costForTwo: "₹560 for two",
        cuisines: ["South Indian", "North Indian"],
        avgRating: 5.5,
        veg: true,
    },
    {
        id: "3477749",
        name: "ChaiPoint",
        cloudinaryImageId: "p4znxkstyrdobxwl6rxa ",
        locality: "Ameerpet",
        areaName: "Narsingi",
        costForTwo: "₹50 for two",
        cuisines: ["South Indian", "North Indian"],
        avgRating: 3.5,
        veg: true,
    }
]

// const bestoffer_Data = [
//     {
//         id: "34777489",
//         name: "Tiffins",
//         cloudinaryImageId: "3967580c0329555334072b18ba3c889c",
//         locality: "Manikonda",
//         areaName: "Narsingi",
//         costForTwo: "₹150 for two",
//         cuisines: ["South Indian", "North Indian", "Thandoori"],
//         avgRating: 4.5,
//         veg: true,
//     },
//     {
//         id: "3477748978",
//         name: "Tiffins",
//         cloudinaryImageId: "8759cb1007417b7df753a2960300cb02",
//         locality: "Manikonda",
//         areaName: "Narsingi",
//         costForTwo: "₹150 for two",
//         cuisines: ["South Indian", "North Indian", "Thandoori"],
//         avgRating: 4.5,
//         veg: true,
//     },
//     {
//         id: "3477748911",
//         name: "Tiffins",
//         cloudinaryImageId: "b7a607f336f0815cd1056262006bb257",
//         locality: "Manikonda",
//         areaName: "Narsingi",
//         costForTwo: "₹150 for two",
//         cuisines: ["South Indian", "North Indian", "Thandoori"],
//         avgRating: 4.5,
//         veg: true,
//     }
// ]
export default restorent_Data;

